<?php

namespace Tests\Feature;

use App\Models\City;
use App\Models\Sightseeing;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Str;
use Tests\TestCase;

class SightseeingTest extends TestCase
{
    use RefreshDatabase;

    private $admin;
    private $employee_read;
    private $employee_write;
    private $created_count = 0;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->services_index_route = route('services.index').'#pills-Sightseeing-tab';
        $this->index_route = route('sightseeings.index');
        $this->create_route = route('sightseeings.create');
        $this->store_route = route('sightseeings.store');
        $this->edit_route = route('sightseeings.edit', ['sightseeing'=>1]);
        $this->update_route = route('sightseeings.update', ['sightseeing'=>1]);

        Artisan::call('testlogs:clear');
        $this->admin = $this->createAdminEmployee();
        $this->employee_write = $this->createEmployeeWithPermission(Sightseeing::PERMISSION_NAME, 'write');
        $this->employee_read = $this->createEmployeeWithPermission(Sightseeing::PERMISSION_NAME, 'read');
    }

    /** @test */
    public function a_guest_is_redirected_to_login()
    {
        $this->get($this->index_route)->assertRedirect(route('login'));
    }

    /** @test */
    public function user_without_permission_is_forbidden()
    {
        $this->actingAs($this->employee_write->user)->get($this->index_route)->assertForbidden();
    }

    /**
     *
     * @test
     * @dataProvider authUserProvider
     */
    public function user_with_permission_can_see_sightseeings_page($auth)
    {
        $auth = $auth == 0 ? $this->admin->user : $this->employee_read->user;
        $count = 3;
        $sightseeings = factory(Sightseeing::class, $count)->create();
        $response = $this->actingAs($auth)->get($this->index_route);

        $response->assertOk();

        $sightseeings_from_view = $this->getDataFromDatatableResponse($response);
        $this->assertNotNull($sightseeings_from_view);
        $this->assertCount($count, $sightseeings_from_view);
        $this->assertCount($count, Sightseeing::all());
    }

    /**
     * @test
     * @dataProvider authUserProvider
     */
    public function user_with_permission_can_paginate_sightseeings($auth)
    {
        $auth = $auth == 0 ? $this->admin->user : $this->employee_read->user;
        $all_count = 10;
        $per_page = 3;
        $sightseeings = factory(Sightseeing::class, $all_count)->create();

        $next_page = '';
        $remaining = $all_count;
        $ids = [];
        for ($i=0;$i<$all_count;$i+=$per_page){
            $url_query = '?length=' . $per_page . '&start=' . $i;
            $url = $this->index_route;
            $url .= $url_query;
            $response = $this->actingAs($auth)->get($url);

            $response->assertOk();

            $sightseeings_from_view = $this->getDataFromDatatableResponse($response);

            //make sure that no raw is sent twice when paginating
            $diff = (array_diff($ids, $sightseeings_from_view->pluck('id')->toArray()));
            $this->assertEquals($diff, $ids);
            $ids = array_merge($ids, $sightseeings_from_view->pluck('id')->toArray());

            $this->assertNotNull($sightseeings_from_view);

            //assert that we got the expected number of raws
            $count_should_be = $remaining >= $per_page ? $per_page : $remaining;
            $remaining -= count($sightseeings_from_view);
            $this->assertCount($count_should_be, $sightseeings_from_view);
        }
    }

    /**
     * @test
     * @dataProvider authUserProvider
     */
    public function user_with_permission_can_search_sightseeing($auth)
    {
        $auth = $auth == 0 ? $this->admin->user : $this->employee_read->user;
        $loops = 13;
        $can_search_by = (new Sightseeing())->can_search_by;
        $can_search_by = array_map(function ($item) {
            return str_replace('sightseeings.', '', $item);
        }, $can_search_by);
        for ($i=0;$i<$loops;$i++){
            $sightseeings = factory(Sightseeing::class, 20)->create();

            $rand_rest = $sightseeings->toArray()[rand(0,9)];
            $rand_name = $rand_rest['name'];
            $rand_word = Arr::random(explode(' ', $rand_name));
            $url_query = '?search[value]=' . $rand_word;

            $response = $this->actingAs($auth)->get($this->index_route.$url_query);
            $response->assertOk();
            $sightseeings_from_view = $this->getDataFromDatatableResponse($response);
            $this->assertNotNull($sightseeings_from_view);
            $this->assertGreaterThan(0, count($sightseeings_from_view));

            //assert searched name exists in the result
            foreach($sightseeings_from_view as $sightseeing){
                $sightseeing = Sightseeing::find($sightseeing->id);
                $found = 0;
                foreach ($can_search_by as $key) {
                    if (stripos($key, '.') !== false) {
                        $parts = explode('.', $key);
                        if (stripos($sightseeing->{$parts[0]}->{$parts[1]}, $rand_word) !== false) {
                            $found++;
                        }
                    } elseif (stripos($sightseeing->{$key}, $rand_word) !== false) {
                        $found++;
                    }
                }
                $this->assertGreaterThan(0, $found);
            }
        }
    }

    /**
     * @test
     * @dataProvider authUserProvider
     */
    public function user_with_permission_can_sort_sightseeings($auth)
    {
        $auth = $auth == 0 ? $this->admin->user : $this->employee_read->user;
        for ($z=0;$z<10;$z++){
            $all_count = 10;
            $sightseeings = factory(Sightseeing::class, $all_count)->create();
            $param = 'name';
            $url_query = '?order[0][dir]=asc&order[0][column]=0&columns[0][data]=' . $param;

            $response = $this->actingAs($auth)->get($this->index_route.$url_query);
            $response->assertOk();

            $sightseeings_from_view = $this->getDataFromDatatableResponse($response);
            $this->assertNotNull($sightseeings_from_view);
            $this->assertGreaterThan(0, count($sightseeings_from_view));

            $sightseeings = $sightseeings_from_view;
            for ($i=0;$i<count($sightseeings);$i++){
                if($i > 0){
                    if (stripos($param, '.') !== false) {
                        $parts = explode('.', $param);
                        $this->greaterThanOrEqual($sightseeings->get($i - 1)->{$parts[0]}->{$parts[1]}, $sightseeings->get($i)->{$parts[0]}->{$parts[1]});
                    } else {
                        $this->greaterThanOrEqual($sightseeings->get($i - 1)->{$param}, $sightseeings->get($i)->{$param});
                    }
                }
            }
        }
    }

    /**
     * @test
     * @dataProvider authUserProvider
     */
    public function user_with_permission_can_delete_sightseeing($auth)
    {
        $auth = $auth == 0 ? $this->admin->user : $this->employee_write->user;
        $data = $this->data();
        $response = $this->actingAs($auth)->post($this->store_route, $data);
        $sightseeing = Sightseeing::first();

        $response = $this->actingAs($auth)->delete($sightseeing->deletePath());
        $response->assertSessionHasNoErrors();
        $response->assertRedirect($this->services_index_route);
        $this->assertNull(Sightseeing::find($sightseeing->id));
        $response->assertSessionHas('success');
    }

    /** @test */
    public function a_guest_cannot_delete_sightseeing()
    {
        $sightseeing = factory(Sightseeing::class)->create();
        $this->delete($sightseeing->deletePath())->assertRedirect(route('login'));
        $this->assertNotNull(Sightseeing::find($sightseeing->id));
    }

    /** @test */
    public function user_without_permission_cannot_delete_sightseeing()
    {
        $sightseeing = factory(Sightseeing::class)->create();
        $this->actingAs($this->employee_read->user)->delete($sightseeing->deletePath())->assertForbidden();
        $this->assertNotNull(Sightseeing::find($sightseeing->id));
    }

    /** @test */
    public function a_guest_cannot_see_add_sightseeing_page()
    {
        $this->get($this->create_route)->assertRedirect(route('login'));
    }

    /** @test */
    public function user_without_permission_cannot_see_add_sightseeing_page()
    {
        $this->actingAs($this->employee_read->user)->get($this->create_route)->assertForbidden();
    }

    /**
     * @test
     * @dataProvider authUserProvider
     */
    public function user_with_permission_can_see_add_sightseeing_page($auth)
    {
        $auth = $auth == 0 ? $this->admin->user : $this->employee_write->user;
        $response = $this->actingAs($auth)->get($this->create_route);
        $response->assertSessionHasNoErrors();
        $response->assertViewIs('sightseeings.create');
        $cities = $this->getDataFromResponse($response, 'cities');
        $this->assertNotNull($cities);
    }

    /** @test */
    public function a_guest_cannot_add_sightseeing()
    {
        $this->post($this->store_route)->assertRedirect(route('login'));
    }

    /** @test */
    public function user_without_permission_cannot_add_sightseeing()
    {
        $this->actingAs($this->employee_read->user)->post($this->store_route)->assertForbidden();
    }

    /**
     * @test
     * @dataProvider authUserProvider
     */
    public function user_with_permission_can_add_sightseeing($auth)
    {
        $auth = $auth == 0 ? $this->admin->user : $this->employee_write->user;
        $data = $this->data();
        $response = $this->actingAs($auth)->post($this->store_route, $data);

        $response->assertSessionHasNoErrors();
        $response->assertRedirect($this->services_index_route);
        $response->assertSessionHas('success');
        $this->assertEquals($this->created_count+1, Sightseeing::count());
        $sightseeing = Sightseeing::first();
        $this->assertData($sightseeing, $data);
    }

    /** @test */
    public function a_guest_cannot_see_edit_sightseeing_page()
    {
        $sightseeing = factory(Sightseeing::class)->create();
        $this->get($sightseeing->editPath())->assertRedirect(route('login'));
    }

    /** @test */
    public function user_without_permission_cannot_see_edit_sightseeing_page()
    {
        $sightseeing = factory(Sightseeing::class)->create();
        $this->actingAs($this->employee_read->user)->get($sightseeing->editPath())->assertForbidden();
    }

    /**
     * @test
     * @dataProvider authUserProvider
     */
    public function user_with_permission_can_see_edit_sightseeing_page($auth)
    {
        $auth = $auth == 0 ? $this->admin->user : $this->employee_write->user;
        $sightseeing = factory(Sightseeing::class)->create();
        $response = $this->actingAs($auth)->get($sightseeing->editPath());
        $response->assertSessionHasNoErrors();
        $response->assertViewIs('sightseeings.edit');
        $sightseeing_from_view = $this->getDataFromResponse($response, 'sightseeing');
        $cities = $this->getDataFromResponse($response, 'cities');
        $this->assertNotNull($cities);
        $this->assertNotNull($sightseeing_from_view);
        $this->assertEquals($sightseeing->id, $sightseeing_from_view->id);
    }

    /** @test */
    public function a_guest_cannot_edit_sightseeing()
    {
        $sightseeing = factory(Sightseeing::class)->create();
        $this->patch($this->update_route)->assertRedirect(route('login'));
    }

    /** @test */
    public function user_without_permission_cannot_edit_sightseeing()
    {
        $sightseeing = factory(Sightseeing::class)->create();
        $this->actingAs($this->employee_read->user)->patch($this->update_route)->assertForbidden();
    }

    /**
     * @test
     * @dataProvider authUserProvider
     */
    public function user_with_permission_can_edit_sightseeing($auth)
    {
        $auth = $auth == 0 ? $this->admin->user : $this->employee_write->user;
        $data = $this->data();
        $response = $this->actingAs($auth)->post($this->store_route, $data);
        $sightseeing = Sightseeing::first();

        $data = $this->update_data();
        $response = $this->actingAs($auth)->patch($this->update_route, $data);

        $response->assertSessionHasNoErrors();
        $response->assertRedirect($this->services_index_route);
        $response->assertSessionHas('success');
        $this->assertCount($this->created_count+1, Sightseeing::all());

        $sightseeing->refresh();
        $this->assertData($sightseeing, $data);
    }




    private function data()
    {
        $data = factory(Sightseeing::class)->make()->toArray();
        $data['buy_price_adult'] = 'EGP '.$data['buy_price_adult'];
        $data['sell_price_adult_vat_exc'] = 'EURO '.$data['sell_price_adult_vat_exc'];
        $data['buy_price_child'] = 'EGP '.$data['buy_price_child'];
        $data['sell_price_child_vat_exc'] = 'EURO '.$data['sell_price_child_vat_exc'];
        return $data;
    }

    private function update_data()
    {
        return $this->data();
    }

    private function assertData($sightseeing, $data)
    {
        foreach ($data as $key => $value) {
            if(in_array($key, ['buy_price_adult','sell_price_adult_vat_exc','buy_price_child','sell_price_child_vat_exc'])){
                $value = trim((string)Str::of($value)->replace(['EGP ', 'EURO ', '%', ','], ''));
            }
            $this->assertEquals($value, $sightseeing->{$key});
        }
    }
}
